/*
 * Fly Machines API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ApiMachineRestart
 */
public class ApiMachineRestartTest {
    private final ApiMachineRestart model = new ApiMachineRestart();

    /**
     * Model tests for ApiMachineRestart
     */
    @Test
    public void testApiMachineRestart() {
        // TODO: test ApiMachineRestart
    }

    /**
     * Test the property 'maxRetries'
     */
    @Test
    public void maxRetriesTest() {
        // TODO: test maxRetries
    }

    /**
     * Test the property 'policy'
     */
    @Test
    public void policyTest() {
        // TODO: test policy
    }

}
