/*
 * Fly Machines API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.ApiHTTPOptions;
import org.openapitools.client.model.ApiProxyProtoOptions;
import org.openapitools.client.model.ApiTLSOptions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ApiMachinePort
 */
public class ApiMachinePortTest {
    private final ApiMachinePort model = new ApiMachinePort();

    /**
     * Model tests for ApiMachinePort
     */
    @Test
    public void testApiMachinePort() {
        // TODO: test ApiMachinePort
    }

    /**
     * Test the property 'endPort'
     */
    @Test
    public void endPortTest() {
        // TODO: test endPort
    }

    /**
     * Test the property 'forceHttps'
     */
    @Test
    public void forceHttpsTest() {
        // TODO: test forceHttps
    }

    /**
     * Test the property 'handlers'
     */
    @Test
    public void handlersTest() {
        // TODO: test handlers
    }

    /**
     * Test the property 'httpOptions'
     */
    @Test
    public void httpOptionsTest() {
        // TODO: test httpOptions
    }

    /**
     * Test the property 'port'
     */
    @Test
    public void portTest() {
        // TODO: test port
    }

    /**
     * Test the property 'proxyProtoOptions'
     */
    @Test
    public void proxyProtoOptionsTest() {
        // TODO: test proxyProtoOptions
    }

    /**
     * Test the property 'startPort'
     */
    @Test
    public void startPortTest() {
        // TODO: test startPort
    }

    /**
     * Test the property 'tlsOptions'
     */
    @Test
    public void tlsOptionsTest() {
        // TODO: test tlsOptions
    }

}
