/*
 * Fly Machines API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.openapitools.client.model.ApiDNSConfig;
import org.openapitools.client.model.ApiFile;
import org.openapitools.client.model.ApiMachineCheck;
import org.openapitools.client.model.ApiMachineGuest;
import org.openapitools.client.model.ApiMachineInit;
import org.openapitools.client.model.ApiMachineMetrics;
import org.openapitools.client.model.ApiMachineMount;
import org.openapitools.client.model.ApiMachineProcess;
import org.openapitools.client.model.ApiMachineRestart;
import org.openapitools.client.model.ApiMachineService;
import org.openapitools.client.model.ApiStatic;
import org.openapitools.client.model.ApiStopConfig;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ApiMachineConfig
 */
public class ApiMachineConfigTest {
    private final ApiMachineConfig model = new ApiMachineConfig();

    /**
     * Model tests for ApiMachineConfig
     */
    @Test
    public void testApiMachineConfig() {
        // TODO: test ApiMachineConfig
    }

    /**
     * Test the property 'autoDestroy'
     */
    @Test
    public void autoDestroyTest() {
        // TODO: test autoDestroy
    }

    /**
     * Test the property 'checks'
     */
    @Test
    public void checksTest() {
        // TODO: test checks
    }

    /**
     * Test the property 'disableMachineAutostart'
     */
    @Test
    public void disableMachineAutostartTest() {
        // TODO: test disableMachineAutostart
    }

    /**
     * Test the property 'dns'
     */
    @Test
    public void dnsTest() {
        // TODO: test dns
    }

    /**
     * Test the property 'env'
     */
    @Test
    public void envTest() {
        // TODO: test env
    }

    /**
     * Test the property 'files'
     */
    @Test
    public void filesTest() {
        // TODO: test files
    }

    /**
     * Test the property 'guest'
     */
    @Test
    public void guestTest() {
        // TODO: test guest
    }

    /**
     * Test the property 'image'
     */
    @Test
    public void imageTest() {
        // TODO: test image
    }

    /**
     * Test the property 'init'
     */
    @Test
    public void initTest() {
        // TODO: test init
    }

    /**
     * Test the property 'metadata'
     */
    @Test
    public void metadataTest() {
        // TODO: test metadata
    }

    /**
     * Test the property 'metrics'
     */
    @Test
    public void metricsTest() {
        // TODO: test metrics
    }

    /**
     * Test the property 'mounts'
     */
    @Test
    public void mountsTest() {
        // TODO: test mounts
    }

    /**
     * Test the property 'processes'
     */
    @Test
    public void processesTest() {
        // TODO: test processes
    }

    /**
     * Test the property 'restart'
     */
    @Test
    public void restartTest() {
        // TODO: test restart
    }

    /**
     * Test the property 'schedule'
     */
    @Test
    public void scheduleTest() {
        // TODO: test schedule
    }

    /**
     * Test the property 'services'
     */
    @Test
    public void servicesTest() {
        // TODO: test services
    }

    /**
     * Test the property 'size'
     */
    @Test
    public void sizeTest() {
        // TODO: test size
    }

    /**
     * Test the property 'standbys'
     */
    @Test
    public void standbysTest() {
        // TODO: test standbys
    }

    /**
     * Test the property 'statics'
     */
    @Test
    public void staticsTest() {
        // TODO: test statics
    }

    /**
     * Test the property 'stopConfig'
     */
    @Test
    public void stopConfigTest() {
        // TODO: test stopConfig
    }

}
