/*
 * Fly Machines API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ApiMachineMount
 */
public class ApiMachineMountTest {
    private final ApiMachineMount model = new ApiMachineMount();

    /**
     * Model tests for ApiMachineMount
     */
    @Test
    public void testApiMachineMount() {
        // TODO: test ApiMachineMount
    }

    /**
     * Test the property 'addSizeGb'
     */
    @Test
    public void addSizeGbTest() {
        // TODO: test addSizeGb
    }

    /**
     * Test the property 'encrypted'
     */
    @Test
    public void encryptedTest() {
        // TODO: test encrypted
    }

    /**
     * Test the property 'extendThresholdPercent'
     */
    @Test
    public void extendThresholdPercentTest() {
        // TODO: test extendThresholdPercent
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'path'
     */
    @Test
    public void pathTest() {
        // TODO: test path
    }

    /**
     * Test the property 'sizeGb'
     */
    @Test
    public void sizeGbTest() {
        // TODO: test sizeGb
    }

    /**
     * Test the property 'sizeGbLimit'
     */
    @Test
    public void sizeGbLimitTest() {
        // TODO: test sizeGbLimit
    }

    /**
     * Test the property 'volume'
     */
    @Test
    public void volumeTest() {
        // TODO: test volume
    }

}
