/*
 * Fly Machines API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ApiTLSOptions
 */
public class ApiTLSOptionsTest {
    private final ApiTLSOptions model = new ApiTLSOptions();

    /**
     * Model tests for ApiTLSOptions
     */
    @Test
    public void testApiTLSOptions() {
        // TODO: test ApiTLSOptions
    }

    /**
     * Test the property 'alpn'
     */
    @Test
    public void alpnTest() {
        // TODO: test alpn
    }

    /**
     * Test the property 'defaultSelfSigned'
     */
    @Test
    public void defaultSelfSignedTest() {
        // TODO: test defaultSelfSigned
    }

    /**
     * Test the property 'versions'
     */
    @Test
    public void versionsTest() {
        // TODO: test versions
    }

}
