/*
 * Fly Machines API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.ApiMachineGuest;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CreateVolumeRequest
 */
public class CreateVolumeRequestTest {
    private final CreateVolumeRequest model = new CreateVolumeRequest();

    /**
     * Model tests for CreateVolumeRequest
     */
    @Test
    public void testCreateVolumeRequest() {
        // TODO: test CreateVolumeRequest
    }

    /**
     * Test the property 'compute'
     */
    @Test
    public void computeTest() {
        // TODO: test compute
    }

    /**
     * Test the property 'encrypted'
     */
    @Test
    public void encryptedTest() {
        // TODO: test encrypted
    }

    /**
     * Test the property 'fstype'
     */
    @Test
    public void fstypeTest() {
        // TODO: test fstype
    }

    /**
     * Test the property 'machinesOnly'
     */
    @Test
    public void machinesOnlyTest() {
        // TODO: test machinesOnly
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'region'
     */
    @Test
    public void regionTest() {
        // TODO: test region
    }

    /**
     * Test the property 'requireUniqueZone'
     */
    @Test
    public void requireUniqueZoneTest() {
        // TODO: test requireUniqueZone
    }

    /**
     * Test the property 'sizeGb'
     */
    @Test
    public void sizeGbTest() {
        // TODO: test sizeGb
    }

    /**
     * Test the property 'snapshotId'
     */
    @Test
    public void snapshotIdTest() {
        // TODO: test snapshotId
    }

    /**
     * Test the property 'snapshotRetention'
     */
    @Test
    public void snapshotRetentionTest() {
        // TODO: test snapshotRetention
    }

    /**
     * Test the property 'sourceVolumeId'
     */
    @Test
    public void sourceVolumeIdTest() {
        // TODO: test sourceVolumeId
    }

}
