/*
 * Fly Machines API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.Volume;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ExtendVolumeResponse
 */
public class ExtendVolumeResponseTest {
    private final ExtendVolumeResponse model = new ExtendVolumeResponse();

    /**
     * Model tests for ExtendVolumeResponse
     */
    @Test
    public void testExtendVolumeResponse() {
        // TODO: test ExtendVolumeResponse
    }

    /**
     * Test the property 'needsRestart'
     */
    @Test
    public void needsRestartTest() {
        // TODO: test needsRestart
    }

    /**
     * Test the property 'volume'
     */
    @Test
    public void volumeTest() {
        // TODO: test volume
    }

}
