/*
 * Fly Machines API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.ListApp;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ListAppsResponse
 */
public class ListAppsResponseTest {
    private final ListAppsResponse model = new ListAppsResponse();

    /**
     * Model tests for ListAppsResponse
     */
    @Test
    public void testListAppsResponse() {
        // TODO: test ListAppsResponse
    }

    /**
     * Test the property 'apps'
     */
    @Test
    public void appsTest() {
        // TODO: test apps
    }

    /**
     * Test the property 'totalApps'
     */
    @Test
    public void totalAppsTest() {
        // TODO: test totalApps
    }

}
