/*
 * Fly Machines API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.ListenSocket;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ProcessStat
 */
public class ProcessStatTest {
    private final ProcessStat model = new ProcessStat();

    /**
     * Model tests for ProcessStat
     */
    @Test
    public void testProcessStat() {
        // TODO: test ProcessStat
    }

    /**
     * Test the property 'command'
     */
    @Test
    public void commandTest() {
        // TODO: test command
    }

    /**
     * Test the property 'cpu'
     */
    @Test
    public void cpuTest() {
        // TODO: test cpu
    }

    /**
     * Test the property 'directory'
     */
    @Test
    public void directoryTest() {
        // TODO: test directory
    }

    /**
     * Test the property 'listenSockets'
     */
    @Test
    public void listenSocketsTest() {
        // TODO: test listenSockets
    }

    /**
     * Test the property 'pid'
     */
    @Test
    public void pidTest() {
        // TODO: test pid
    }

    /**
     * Test the property 'rss'
     */
    @Test
    public void rssTest() {
        // TODO: test rss
    }

    /**
     * Test the property 'rtime'
     */
    @Test
    public void rtimeTest() {
        // TODO: test rtime
    }

    /**
     * Test the property 'stime'
     */
    @Test
    public void stimeTest() {
        // TODO: test stime
    }

}
