/*
 * Fly Machines API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Volume
 */
public class VolumeTest {
    private final Volume model = new Volume();

    /**
     * Model tests for Volume
     */
    @Test
    public void testVolume() {
        // TODO: test Volume
    }

    /**
     * Test the property 'attachedAllocId'
     */
    @Test
    public void attachedAllocIdTest() {
        // TODO: test attachedAllocId
    }

    /**
     * Test the property 'attachedMachineId'
     */
    @Test
    public void attachedMachineIdTest() {
        // TODO: test attachedMachineId
    }

    /**
     * Test the property 'blockSize'
     */
    @Test
    public void blockSizeTest() {
        // TODO: test blockSize
    }

    /**
     * Test the property 'blocks'
     */
    @Test
    public void blocksTest() {
        // TODO: test blocks
    }

    /**
     * Test the property 'blocksAvail'
     */
    @Test
    public void blocksAvailTest() {
        // TODO: test blocksAvail
    }

    /**
     * Test the property 'blocksFree'
     */
    @Test
    public void blocksFreeTest() {
        // TODO: test blocksFree
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'encrypted'
     */
    @Test
    public void encryptedTest() {
        // TODO: test encrypted
    }

    /**
     * Test the property 'fstype'
     */
    @Test
    public void fstypeTest() {
        // TODO: test fstype
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'region'
     */
    @Test
    public void regionTest() {
        // TODO: test region
    }

    /**
     * Test the property 'sizeGb'
     */
    @Test
    public void sizeGbTest() {
        // TODO: test sizeGb
    }

    /**
     * Test the property 'snapshotRetention'
     */
    @Test
    public void snapshotRetentionTest() {
        // TODO: test snapshotRetention
    }

    /**
     * Test the property 'state'
     */
    @Test
    public void stateTest() {
        // TODO: test state
    }

    /**
     * Test the property 'zone'
     */
    @Test
    public void zoneTest() {
        // TODO: test zone
    }

}
