/*
 * Fly Machines API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * ApiMachineMount
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-12-31T17:25:53.139932930Z[Europe/London]")
public class ApiMachineMount {
  public static final String SERIALIZED_NAME_ADD_SIZE_GB = "add_size_gb";
  @SerializedName(SERIALIZED_NAME_ADD_SIZE_GB)
  private Integer addSizeGb;

  public static final String SERIALIZED_NAME_ENCRYPTED = "encrypted";
  @SerializedName(SERIALIZED_NAME_ENCRYPTED)
  private Boolean encrypted;

  public static final String SERIALIZED_NAME_EXTEND_THRESHOLD_PERCENT = "extend_threshold_percent";
  @SerializedName(SERIALIZED_NAME_EXTEND_THRESHOLD_PERCENT)
  private Integer extendThresholdPercent;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_PATH = "path";
  @SerializedName(SERIALIZED_NAME_PATH)
  private String path;

  public static final String SERIALIZED_NAME_SIZE_GB = "size_gb";
  @SerializedName(SERIALIZED_NAME_SIZE_GB)
  private Integer sizeGb;

  public static final String SERIALIZED_NAME_SIZE_GB_LIMIT = "size_gb_limit";
  @SerializedName(SERIALIZED_NAME_SIZE_GB_LIMIT)
  private Integer sizeGbLimit;

  public static final String SERIALIZED_NAME_VOLUME = "volume";
  @SerializedName(SERIALIZED_NAME_VOLUME)
  private String volume;

  public ApiMachineMount() {
  }

  public ApiMachineMount addSizeGb(Integer addSizeGb) {
    this.addSizeGb = addSizeGb;
    return this;
  }

   /**
   * Get addSizeGb
   * @return addSizeGb
  **/
  @javax.annotation.Nullable
  public Integer getAddSizeGb() {
    return addSizeGb;
  }

  public void setAddSizeGb(Integer addSizeGb) {
    this.addSizeGb = addSizeGb;
  }


  public ApiMachineMount encrypted(Boolean encrypted) {
    this.encrypted = encrypted;
    return this;
  }

   /**
   * Get encrypted
   * @return encrypted
  **/
  @javax.annotation.Nullable
  public Boolean getEncrypted() {
    return encrypted;
  }

  public void setEncrypted(Boolean encrypted) {
    this.encrypted = encrypted;
  }


  public ApiMachineMount extendThresholdPercent(Integer extendThresholdPercent) {
    this.extendThresholdPercent = extendThresholdPercent;
    return this;
  }

   /**
   * Get extendThresholdPercent
   * @return extendThresholdPercent
  **/
  @javax.annotation.Nullable
  public Integer getExtendThresholdPercent() {
    return extendThresholdPercent;
  }

  public void setExtendThresholdPercent(Integer extendThresholdPercent) {
    this.extendThresholdPercent = extendThresholdPercent;
  }


  public ApiMachineMount name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @javax.annotation.Nullable
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }


  public ApiMachineMount path(String path) {
    this.path = path;
    return this;
  }

   /**
   * Get path
   * @return path
  **/
  @javax.annotation.Nullable
  public String getPath() {
    return path;
  }

  public void setPath(String path) {
    this.path = path;
  }


  public ApiMachineMount sizeGb(Integer sizeGb) {
    this.sizeGb = sizeGb;
    return this;
  }

   /**
   * Get sizeGb
   * @return sizeGb
  **/
  @javax.annotation.Nullable
  public Integer getSizeGb() {
    return sizeGb;
  }

  public void setSizeGb(Integer sizeGb) {
    this.sizeGb = sizeGb;
  }


  public ApiMachineMount sizeGbLimit(Integer sizeGbLimit) {
    this.sizeGbLimit = sizeGbLimit;
    return this;
  }

   /**
   * Get sizeGbLimit
   * @return sizeGbLimit
  **/
  @javax.annotation.Nullable
  public Integer getSizeGbLimit() {
    return sizeGbLimit;
  }

  public void setSizeGbLimit(Integer sizeGbLimit) {
    this.sizeGbLimit = sizeGbLimit;
  }


  public ApiMachineMount volume(String volume) {
    this.volume = volume;
    return this;
  }

   /**
   * Get volume
   * @return volume
  **/
  @javax.annotation.Nullable
  public String getVolume() {
    return volume;
  }

  public void setVolume(String volume) {
    this.volume = volume;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ApiMachineMount apiMachineMount = (ApiMachineMount) o;
    return Objects.equals(this.addSizeGb, apiMachineMount.addSizeGb) &&
        Objects.equals(this.encrypted, apiMachineMount.encrypted) &&
        Objects.equals(this.extendThresholdPercent, apiMachineMount.extendThresholdPercent) &&
        Objects.equals(this.name, apiMachineMount.name) &&
        Objects.equals(this.path, apiMachineMount.path) &&
        Objects.equals(this.sizeGb, apiMachineMount.sizeGb) &&
        Objects.equals(this.sizeGbLimit, apiMachineMount.sizeGbLimit) &&
        Objects.equals(this.volume, apiMachineMount.volume);
  }

  @Override
  public int hashCode() {
    return Objects.hash(addSizeGb, encrypted, extendThresholdPercent, name, path, sizeGb, sizeGbLimit, volume);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ApiMachineMount {\n");
    sb.append("    addSizeGb: ").append(toIndentedString(addSizeGb)).append("\n");
    sb.append("    encrypted: ").append(toIndentedString(encrypted)).append("\n");
    sb.append("    extendThresholdPercent: ").append(toIndentedString(extendThresholdPercent)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    path: ").append(toIndentedString(path)).append("\n");
    sb.append("    sizeGb: ").append(toIndentedString(sizeGb)).append("\n");
    sb.append("    sizeGbLimit: ").append(toIndentedString(sizeGbLimit)).append("\n");
    sb.append("    volume: ").append(toIndentedString(volume)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("add_size_gb");
    openapiFields.add("encrypted");
    openapiFields.add("extend_threshold_percent");
    openapiFields.add("name");
    openapiFields.add("path");
    openapiFields.add("size_gb");
    openapiFields.add("size_gb_limit");
    openapiFields.add("volume");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to ApiMachineMount
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ApiMachineMount.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ApiMachineMount is not found in the empty JSON string", ApiMachineMount.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ApiMachineMount.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ApiMachineMount` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("name") != null && !jsonObj.get("name").isJsonNull()) && !jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      if ((jsonObj.get("path") != null && !jsonObj.get("path").isJsonNull()) && !jsonObj.get("path").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `path` to be a primitive type in the JSON string but got `%s`", jsonObj.get("path").toString()));
      }
      if ((jsonObj.get("volume") != null && !jsonObj.get("volume").isJsonNull()) && !jsonObj.get("volume").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `volume` to be a primitive type in the JSON string but got `%s`", jsonObj.get("volume").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ApiMachineMount.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ApiMachineMount' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ApiMachineMount> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ApiMachineMount.class));

       return (TypeAdapter<T>) new TypeAdapter<ApiMachineMount>() {
           @Override
           public void write(JsonWriter out, ApiMachineMount value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ApiMachineMount read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of ApiMachineMount given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of ApiMachineMount
  * @throws IOException if the JSON string is invalid with respect to ApiMachineMount
  */
  public static ApiMachineMount fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ApiMachineMount.class);
  }

 /**
  * Convert an instance of ApiMachineMount to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

