/*
 * Fly Machines API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * ApiStatic
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-12-31T17:25:53.139932930Z[Europe/London]")
public class ApiStatic {
  public static final String SERIALIZED_NAME_GUEST_PATH = "guest_path";
  @SerializedName(SERIALIZED_NAME_GUEST_PATH)
  private String guestPath;

  public static final String SERIALIZED_NAME_URL_PREFIX = "url_prefix";
  @SerializedName(SERIALIZED_NAME_URL_PREFIX)
  private String urlPrefix;

  public ApiStatic() {
  }

  public ApiStatic guestPath(String guestPath) {
    this.guestPath = guestPath;
    return this;
  }

   /**
   * Get guestPath
   * @return guestPath
  **/
  @javax.annotation.Nonnull
  public String getGuestPath() {
    return guestPath;
  }

  public void setGuestPath(String guestPath) {
    this.guestPath = guestPath;
  }


  public ApiStatic urlPrefix(String urlPrefix) {
    this.urlPrefix = urlPrefix;
    return this;
  }

   /**
   * Get urlPrefix
   * @return urlPrefix
  **/
  @javax.annotation.Nonnull
  public String getUrlPrefix() {
    return urlPrefix;
  }

  public void setUrlPrefix(String urlPrefix) {
    this.urlPrefix = urlPrefix;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ApiStatic apiStatic = (ApiStatic) o;
    return Objects.equals(this.guestPath, apiStatic.guestPath) &&
        Objects.equals(this.urlPrefix, apiStatic.urlPrefix);
  }

  @Override
  public int hashCode() {
    return Objects.hash(guestPath, urlPrefix);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ApiStatic {\n");
    sb.append("    guestPath: ").append(toIndentedString(guestPath)).append("\n");
    sb.append("    urlPrefix: ").append(toIndentedString(urlPrefix)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("guest_path");
    openapiFields.add("url_prefix");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("guest_path");
    openapiRequiredFields.add("url_prefix");
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to ApiStatic
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ApiStatic.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ApiStatic is not found in the empty JSON string", ApiStatic.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ApiStatic.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ApiStatic` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : ApiStatic.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("guest_path").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `guest_path` to be a primitive type in the JSON string but got `%s`", jsonObj.get("guest_path").toString()));
      }
      if (!jsonObj.get("url_prefix").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `url_prefix` to be a primitive type in the JSON string but got `%s`", jsonObj.get("url_prefix").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ApiStatic.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ApiStatic' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ApiStatic> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ApiStatic.class));

       return (TypeAdapter<T>) new TypeAdapter<ApiStatic>() {
           @Override
           public void write(JsonWriter out, ApiStatic value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ApiStatic read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of ApiStatic given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of ApiStatic
  * @throws IOException if the JSON string is invalid with respect to ApiStatic
  */
  public static ApiStatic fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ApiStatic.class);
  }

 /**
  * Convert an instance of ApiStatic to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

