/*
 * Fly Machines API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * ApiTLSOptions
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-12-31T17:25:53.139932930Z[Europe/London]")
public class ApiTLSOptions {
  public static final String SERIALIZED_NAME_ALPN = "alpn";
  @SerializedName(SERIALIZED_NAME_ALPN)
  private List<String> alpn;

  public static final String SERIALIZED_NAME_DEFAULT_SELF_SIGNED = "default_self_signed";
  @SerializedName(SERIALIZED_NAME_DEFAULT_SELF_SIGNED)
  private Boolean defaultSelfSigned;

  public static final String SERIALIZED_NAME_VERSIONS = "versions";
  @SerializedName(SERIALIZED_NAME_VERSIONS)
  private List<String> versions;

  public ApiTLSOptions() {
  }

  public ApiTLSOptions alpn(List<String> alpn) {
    this.alpn = alpn;
    return this;
  }

  public ApiTLSOptions addAlpnItem(String alpnItem) {
    if (this.alpn == null) {
      this.alpn = new ArrayList<>();
    }
    this.alpn.add(alpnItem);
    return this;
  }

   /**
   * Get alpn
   * @return alpn
  **/
  @javax.annotation.Nullable
  public List<String> getAlpn() {
    return alpn;
  }

  public void setAlpn(List<String> alpn) {
    this.alpn = alpn;
  }


  public ApiTLSOptions defaultSelfSigned(Boolean defaultSelfSigned) {
    this.defaultSelfSigned = defaultSelfSigned;
    return this;
  }

   /**
   * Get defaultSelfSigned
   * @return defaultSelfSigned
  **/
  @javax.annotation.Nullable
  public Boolean getDefaultSelfSigned() {
    return defaultSelfSigned;
  }

  public void setDefaultSelfSigned(Boolean defaultSelfSigned) {
    this.defaultSelfSigned = defaultSelfSigned;
  }


  public ApiTLSOptions versions(List<String> versions) {
    this.versions = versions;
    return this;
  }

  public ApiTLSOptions addVersionsItem(String versionsItem) {
    if (this.versions == null) {
      this.versions = new ArrayList<>();
    }
    this.versions.add(versionsItem);
    return this;
  }

   /**
   * Get versions
   * @return versions
  **/
  @javax.annotation.Nullable
  public List<String> getVersions() {
    return versions;
  }

  public void setVersions(List<String> versions) {
    this.versions = versions;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ApiTLSOptions apiTLSOptions = (ApiTLSOptions) o;
    return Objects.equals(this.alpn, apiTLSOptions.alpn) &&
        Objects.equals(this.defaultSelfSigned, apiTLSOptions.defaultSelfSigned) &&
        Objects.equals(this.versions, apiTLSOptions.versions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(alpn, defaultSelfSigned, versions);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ApiTLSOptions {\n");
    sb.append("    alpn: ").append(toIndentedString(alpn)).append("\n");
    sb.append("    defaultSelfSigned: ").append(toIndentedString(defaultSelfSigned)).append("\n");
    sb.append("    versions: ").append(toIndentedString(versions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("alpn");
    openapiFields.add("default_self_signed");
    openapiFields.add("versions");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to ApiTLSOptions
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ApiTLSOptions.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ApiTLSOptions is not found in the empty JSON string", ApiTLSOptions.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ApiTLSOptions.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ApiTLSOptions` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // ensure the optional json data is an array if present
      if (jsonObj.get("alpn") != null && !jsonObj.get("alpn").isJsonNull() && !jsonObj.get("alpn").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `alpn` to be an array in the JSON string but got `%s`", jsonObj.get("alpn").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("versions") != null && !jsonObj.get("versions").isJsonNull() && !jsonObj.get("versions").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `versions` to be an array in the JSON string but got `%s`", jsonObj.get("versions").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ApiTLSOptions.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ApiTLSOptions' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ApiTLSOptions> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ApiTLSOptions.class));

       return (TypeAdapter<T>) new TypeAdapter<ApiTLSOptions>() {
           @Override
           public void write(JsonWriter out, ApiTLSOptions value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ApiTLSOptions read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of ApiTLSOptions given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of ApiTLSOptions
  * @throws IOException if the JSON string is invalid with respect to ApiTLSOptions
  */
  public static ApiTLSOptions fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ApiTLSOptions.class);
  }

 /**
  * Convert an instance of ApiTLSOptions to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

