/*
 * Fly Machines API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.App;
import org.openapitools.client.model.CreateAppRequest;
import org.openapitools.client.model.ErrorResponse;
import org.openapitools.client.model.ListAppsResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AppsApi
 */
@Disabled
public class AppsApiTest {

    private final AppsApi api = new AppsApi();

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void appsCreateTest() throws ApiException {
        CreateAppRequest request = null;
        api.appsCreate(request);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void appsDeleteTest() throws ApiException {
        String appName = null;
        api.appsDelete(appName);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void appsListTest() throws ApiException {
        String orgSlug = null;
        ListAppsResponse response = api.appsList(orgSlug);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void appsShowTest() throws ApiException {
        String appName = null;
        App response = api.appsShow(appName);
        // TODO: test validations
    }

}
