/*
 * Fly Machines API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.CreateVolumeRequest;
import org.openapitools.client.model.ErrorResponse;
import org.openapitools.client.model.ExtendVolumeRequest;
import org.openapitools.client.model.ExtendVolumeResponse;
import org.openapitools.client.model.UpdateVolumeRequest;
import org.openapitools.client.model.Volume;
import org.openapitools.client.model.VolumeSnapshot;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for VolumesApi
 */
@Disabled
public class VolumesApiTest {

    private final VolumesApi api = new VolumesApi();

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createVolumeSnapshotTest() throws ApiException {
        String appName = null;
        String volumeId = null;
        api.createVolumeSnapshot(appName, volumeId);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void volumeDeleteTest() throws ApiException {
        String appName = null;
        String volumeId = null;
        Volume response = api.volumeDelete(appName, volumeId);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void volumesCreateTest() throws ApiException {
        String appName = null;
        CreateVolumeRequest request = null;
        Volume response = api.volumesCreate(appName, request);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void volumesExtendTest() throws ApiException {
        String appName = null;
        String volumeId = null;
        ExtendVolumeRequest request = null;
        ExtendVolumeResponse response = api.volumesExtend(appName, volumeId, request);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void volumesGetByIdTest() throws ApiException {
        String appName = null;
        String volumeId = null;
        Volume response = api.volumesGetById(appName, volumeId);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void volumesListTest() throws ApiException {
        String appName = null;
        List<Volume> response = api.volumesList(appName);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void volumesListSnapshotsTest() throws ApiException {
        String appName = null;
        String volumeId = null;
        List<VolumeSnapshot> response = api.volumesListSnapshots(appName, volumeId);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void volumesUpdateTest() throws ApiException {
        String appName = null;
        String volumeId = null;
        UpdateVolumeRequest request = null;
        Volume response = api.volumesUpdate(appName, volumeId, request);
        // TODO: test validations
    }

}
